### ISSUE TITLE
May 2021 rough plan of work

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#1335]
This is the rough list of work for the month of May.

- [ ] Failing on #r "nuget" puts the kernel in unusable state (#1181)
- [x] Pin VS Code extension in stable channel to a specific `dotnet-interactive` version (#1338)
- [ ] Finish JavaScript kernel client side command handling
- [ ] Spike: Try .NET kernel
- [ ] Update home page & extension splash page
- [x] Track issue microsoft/vscode#124507
