### ISSUE TITLE
June 2021 rough plan of work

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#1407]
- [ ] Failing on #r "nuget" puts the kernel in unusable state (#1181)
- [x] Finish JavaScript kernel client side command handling
- [ ] Spike: Try .NET kernel
- [x] User prompts in VS Code
- [ ] Update `dotnet-try` to .NET 5
- [ ] IntelliSense in Visual Studio Code is slow comparing to .cs files (#1391)
- [x] Review notebook serialization (#1396)
  - [ ] Differentiate deserialization APIs for .dib versus .ipynb (#1427) 
- [ ] #1476
