### ISSUE TITLE
September rough plan of work (2023)

### ISSUE THREAD

**Issue by shyamnamboodiripad** [dotnet/interactive#3164]
- [ ] #3136 @shyamnamboodiripad @jonsequitur @colombod 
    - [ ] #3144 @shyamnamboodiripad 
    - [x] #2095 @jonsequitur
    - [x] #1541 @ocallesp 
 - [ ] #992 @jonsequitur 
- [x] #2387 @jonsequitur @colombod 
- [ ] #3141 @jonsequitur @shyamnamboodiripad @bleaphar
- [ ] #3124 @shyamnamboodiripad 
- [ ] #2683 follow-up only if we receive user feedback @colombod 

-------------------------------------------------- stretch ------------------------------------------
- [ ] #747 @ocallesp @shyamnamboodiripad

**Comment by heartacker** [comment]
HI, THIS IS INDEED 
https://github.com/dotnet/interactive/issues/2874
