### ISSUE TITLE
Usability improvements for samples work

### ISSUE THREAD

**Issue by jonsequitur** [dotnet/interactive#3212]
This issue collects small features and usability improvements intended to make planned sample notebooks more concise and easier to use.

### Intelligent app development issues
- [x] #3194
- [ ] #3211
- [ ] https://github.com/colombod/dotnet-interactive-extension-lab/issues/38
- [x] API for token count  for specific models (related PRs :  #3223, #3217)
- [x] API to truncate text using token count (with optional overlapping) (related PRs :  #3217)
- [x] API to split long text using token count (with optional overlapping) (related PRs :  #3217)
- [x] Linq extensions for slicing and chunking  (related PRs :  #3217)
- [x] Search utilities over collections using similarity scores (like cosine similarity)  (related PRs :  #3217)
- [x] Generate JsonSchema from methods for GPT Function calls (see  #3243)
- [x] Automate function calls from GPT function results (see #3243)
- [ ] Access to json documents is a lot of code, need some indexer and / or xpath selection (see #3243)
- [ ] GPT Function does not respect argument schema, array of strings are completed as single string and enum values are ignored
- [ ] Azure OpenAI SDK `FunctionDefinition` and `FunctionCall` are hard to use as they partial deserialize the json paylaod and leave the rest as plain strings (`FunctionDefinition.Parameters` and `FunctionCall.Arguments` are not usable objects but binary paylaod or string)
- [x] Ability to sample at random from collections (related PRs #3294 )
- [ ] simplify calculations like centroids (related Prs #3298 )

### Data preparation issues
- [ ] create float[] column types in dataframe (needed for data prep)

### Ecosystem issues
- [ ] Support for easy scraping of wikipedia (maybe using this https://github.com/CXuesong/WikiClientLibrary/tree/6be126af214b60367637a804863b7d7f46f649fe)
- [ ] pdf parsing / extraction
- [ ] arxiv search
